### PR TITLE
Proposal 04

### PR DESCRIPTION
**Pull request by Blady-Com**
Hello, I've managed to pass most options as environment variables but some ones as configure or setup options need to be passed in makefile.
I hope it is acceptable for you or maybe is there an other way?
Like that I succeeded to build and run all 20.2 targets.
Best, Pascal.

### CODE REVIEW

**Comment by steve-cs** [comment]
That looks like the simplest way to get started on supporting external configure/build options.  I'm thinking maybe that --with-GL=no should then be a default gtkada option.  I'm also thinking maybe that I should expose *-options for all of the modules.

I'm curious, what then are the options necessary for building 20.2 on OSX?

**Comment by steve-cs** [comment]
@Blady-Com, take a look at gnat-builder commit https://github.com/steve-cs/gnat-builder/commit/6d750d4ee43b83643ff1b68acffc57f7abb8c2b9 and see if it does what you need.  I've only tested it to see that it doesn't break my builds.  It should be nearly identical to what you proposed.  Please note that I've also removed the dependency on a separate gnat source repository.  Instead the spark2014 build uses gnat from inside the gcc source instead.

**Comment by Blady-Com** [comment]
> I'm curious, what then are the options necessary for building 20.2 on OSX?

Hello Steve,
Mostly for the underlying graphic system which is by default X11 well supported by macOS but I prefer that GTKAda runs on the native Quartz graphic system and the same for clang I prefer to set the native one, and also I set all debug options.
Best Pascal.

**Comment by Blady-Com** [comment]
> @Blady-Com, take a look at gnat-builder commit [6d750d4](https://github.com/steve-cs/gnat-builder/commit/6d750d4ee43b83643ff1b68acffc57f7abb8c2b9) and see if it does what you need. I've only tested it to see that it doesn't break my builds. It should be nearly identical to what you proposed. Please note that I've also removed the dependency on a separate gnat source repository. Instead the spark2014 build uses gnat from inside the gcc source instead.

Hello Steve,
It seems to be correct :-)
I plan to launch a complete build for the next Adacore release 20.3.
By the way, I was puzzled by libadalang-version, what is it for (instead adacore-version)?
And I was wondering to keep .git in repository in order to help build tuning (to able to select a specific commit)?
Thanks, Pascal.

**Comment by steve-cs** [comment]
> By the way, I was puzzled by libadalang-version, what is it for (instead adacore-version)?

libadalang is still under very active development and doesn't have a stable API in development.  This can break GPS development builds for significant periods of time.  Adacore maintains a libadalang/stable branch so that gps/master can build nightly.  This should only be needed for adacore-version=master.

>And I was wondering to keep .git in repository in order to help build tuning (to able to select a specific commit)?

The problem for me was that changes on Azure (used by Github Actions) caused the nightly make release (including full bootstrap) build to run out of storage resources at the end while building spark2014.  Only cloning to --depth=1 and adding extra *-clean in the bootstrap provided a lot of breathing room.  The workaround is to manage *-src outside of gnat-builder and to avoid using make clean or make <module>-clean.  The alternative to clean is "rm -rf <module>-build".  Alternatively I thought that setting <module>-version=<commit> should still work to fetch a specific commit.

**Pull request closed without merging**
