### PR TITLE
Add support for GNATColl and GTKAda options.

### PR DESCRIPTION
**Pull request by Blady-Com**

### CODE REVIEW

**Comment by steve-cs** [comment]
This needs more thought.  Some of my concerns are as follows.

I have mixed feelings about adding lots of configuration at the expense of losing sight of "the right way" to do things.

The balance of global options and per module options.  For instance should "prefix" be a global option and should it be applied to all modules.  There are reasons why prefix isn't currently applied in gnatcore-core-install (or gnatcore-core setup).  Basically things get very fragile if gnatcoll isn't installed in the same base prefix as the compilers.  Mixing Adacore versions during the build makes this worse.

Adacore isn't consistent about how and where build and install options are applied; e.g. configure, setup, build and/or install.  I don't want to add to that confusion.

There are no doubt answers to these (and other minor concerns).  I'll think about it.

**Comment by steve-cs** [comment]
I've forced prefix for gnatcoll-core install.  It turns out that it was the only module where I wasn't forcing it before.  So it makes more sense to be consistent than have it default to the compiler install location.  Thank you.

I don't understand the need for per module options.  More specifically, I'm of the opinion that if the tool chain (make release) doesn't build with the default options then it is likely an AdaCore bug that needs to be fixed or understood first.  Or maintained in a separate branch as I can't test or support OSX at the present time.

**Comment by Blady-Com** [comment]
Hello Steve,

I build the librairies with debug options.
I use GNAT Community 2019 thus I have some issues with licences that provoque building failures as -gnatwe is set often by default with debug.

So here are a number of my commands:
```
make adacore-version=19.2 os=darwin gtkada prefix=$instxada gtkada-options=--enable-build=Debug
make adacore-version=19.2 os=darwin gnatcoll-core-build prefix=$instxada gnatcoll-core-options="BUILD=DEBUG GPRBUILD_OPTIONS=-gnatwn"
make adacore-version=19.2 os=darwin gnatcoll-core gnatcoll-core-options="BUILD=DEBUG GPRBUILD_OPTIONS=-gnatwn"
make adacore-version=19.2 os=darwin gnatcoll-bindings gnatcoll-bindings-options="--debug --gpr-opts=-gnatwn"
make adacore-version=19.2 os=darwin gnatcoll-db-build prefix=$instxada gnatcoll-db-options="BUILD=DEBUG GNATCOLL_SQLITE=external DB_BACKEND=sqlite"
```
These libraries among many others are included in a yearly published package "ready to install" Ada libraries and tools for macOS synchronized with AdaCore Gnat Community release:
https://hermes.gwu.edu/cgi-bin/wa?A2=ind1809&L=GNAT-OSX&P=68

This first time, your makefile is helping greatly building some items.
It would be nice if it can include options :-)
I have some more ideas, for instance, adding documentation generation, Templates Parser, Florist...

Thanks, Pascal.

**Comment by steve-cs** [comment]
Possible work arounds might include:

1. Building a GPL with linking exceptions compiler and run time instead of using the pure GPL community compiler.   My understanding is that GNAT Community 2020 will not include Darwin/OSX binaries.  I think you might have to face this eventually anyway.

2.  "export Build=Production && make os=darwin gnatcoll-core" to disable the Debug build.  I've used that to work around the occasional warnings that crop up building older releases with newer or development compilers.

3.  I wonder if passing other options as environment variables rather than make variables to gnat-builder isn't feasible and more direct way to work around your specific issues.

**Pull request closed without merging**
